---
- include: common.yml

- name: Check the PiRogue has 2 Wlan interfaces
  fail:
    msg: "The PiRogue does not have wlan1 interface - {{ansible_interfaces}}"
  when: '"wlan1" not in ansible_interfaces'

- name: Install PiRogue files
  git:
    repo: https://github.com/U039b/PiRogue.git
    dest: /usr/share/PiRogue
    force: yes

- name: Change hostname
  hostname:
    name: PiRogue

- name: hostname is resolvable
  lineinfile:
    path: "/etc/hosts"
    regexp: "^127\\.0\\.0\\.1"
    line: "127.0.0.1  hostname PiRogue"

- name: Fix locale issue
  lineinfile:
    path: /root/.bashrc
    regexp: '^export LC_ALL='
    line: 'export LC_ALL="en_US.UTF-8"'

- name: locale en_US.UTF-8 UTF-8 is available
  lineinfile:
    path: "/etc/locale.gen"
    regexp: ".*en_US\\.UTF\\-8 UTF\\-8"
    line: "en_US.UTF-8 UTF-8"
  notify: reload locales

- name: Configure wlan1 interface
  copy:
    src: interfaces
    dest: /etc/network/interfaces

- name: Install dnsmasq
  apt:
    pkg: "{{item}}"
    state: "present"
    update_cache: yes
    cache_valid_time: 10800
  with_items:
    - dnsmasq

- name: Enable service hostapd and ensure it is not masked
  systemd:
    name: hostapd
    enabled: yes
    masked: no

- name: Enable service dnsmasq and ensure it is not masked
  systemd:
    name: dnsmasq
    enabled: yes
    masked: no

- name: Configure dnsmasq
  file:
    src: /usr/share/PiRogue/dnsmasq/dnsmasq.conf
    dest: /etc/dnsmasq.d/pirogue.conf
    state: link

- name: /usr/share/PiRogue/hostapd/ folder exists
  file:
    path: "/usr/share/PiRogue/hostapd/"
    state: "directory"
    
- name: hostapd configuration file is present
  template:
    src: "hostapd.conf.j2"
    dest: "/usr/share/PiRogue/hostapd/hostapd.conf"
    mode: "0760"
    owner: root
    group: root
  notify: reload hostapd

- name: hostapd daemon is configured
  lineinfile:
    path: /etc/default/hostapd
    regexp: '^DAEMON_CONF='
    line: 'DAEMON_CONF="/usr/share/PiRogue/hostapd/hostapd.conf"'

- name: bash script are executable
  file:
    path: "{{ item }}"
    mode: "0750"
  loop:
    - /usr/share/PiRogue/install.sh
    - /usr/share/PiRogue/proxy/transparent.sh
    - /usr/share/PiRogue/proxy/stop_transparent.sh
    - /usr/share/PiRogue/firewall/90pirogue.sh

- name: Configure network routing
  copy:
    src: sysctl_pyrogue.conf
    dest: /etc/sysctl.d/pirogue.conf

- name: Configure modules
  copy:
    src: modules
    dest: /etc/modules

- name: Add a reboot task in cron table displaying the boot screen
  copy:
    src: cron_pirogue
    dest: /etc/cron.d/pirogue

- include: "enable-i2c.yml"

- name: Add the service displaying details on screen
  file:
    src: /usr/share/PiRogue/oled-screen/display_details.service
    dest: /etc/systemd/system/display_details.service
    state: link

- name: Enable the service displaying details on screen
  systemd:
    name: display_details
    daemon_reload: yes
    enabled: yes

- name: Clone SSD1306 library
  git:
    repo: https://github.com/adafruit/Adafruit_Python_SSD1306.git
    dest: /tmp/ssd1306

- name: Install SSD1306 library
  shell: cd /tmp/ssd1306; python setup.py install

- name: Install python tools
  pip: name={{item}}
  with_items:
    - RPi.GPIO

- name: enable camera (step 1)
  lineinfile:
    path: "/boot/config.txt"
    regexp: "^start_x"
    line: "start_x=1"

- name: enable camera (step 2)
  lineinfile:
    path: "/boot/config.txt"
    regexp: "^gpu_mem"
    line: "gpu_mem=128"

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
